# Edit this file trigger a new group build in Builder.

[bcrypt]
plan_path = "bcrypt"
paths = [
  "bcrypt/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[botocore]
plan_path = "botocore"
paths = [
  "botocore/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[cffi]
plan_path = "cffi"
paths = [
  "cffi/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[Cython]
plan_path = "Cython"
paths = [
  "Cython/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[grpcio]
plan_path = "grpcio"
paths = [
  "grpcio/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[numpy]
plan_path = "numpy"
paths = [
  "numpy/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[pandas]
plan_path = "pandas"
paths = [
  "pandas/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[scaffolding-pip]
plan_path = "scaffolding-pip"
paths = [
  "scaffolding-pip/*",
  ".bldr.toml"
]

[scikit-learn]
plan_path = "scikit-learn"
paths = [
  "scikit-learn/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[scipy]
plan_path = "scipy"
paths = [
  "scipy/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[six]
plan_path = "six"
paths = [
  "six/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]

[tensorflow]
plan_path = "tensorflow"
paths = [
  "tensorflow/*",
  "scaffolding-pip/*",
  ".bldr.toml"
]
